### ISSUE TITLE
New MQTT backend: UI changes to-do list

### ISSUE THREAD

**Issue by Depau** [Hypfer/Valetudo#803]
This issue is a to-do list for things that will have to be adjusted in the UI once #787 is merged.
I will extend it as needed.

- MQTT settings page
  - [x] Toggles and settings for Homie and Hass
  - [x] Toggle for "clean" MQTT setting (#640)

- Other
  - [ ] Evaluate options to use the new status subscription code for pushing status events to the UI

**Comment by jorritsmit** [comment]
I have an issue where my mqtt settings are cleared at random, will that be solved by this?
